--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021.11.19. 11:52:31
-- Server version: 5.5.5-10.4.6-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS `e-budget`;

CREATE DATABASE `e-budget`
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE `e-budget`;

--
-- Create table `currencies`
--
CREATE TABLE currencies (
  id INT(11) NOT NULL AUTO_INCREMENT,
  currency_code CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `currency_code` on table `currencies`
--
ALTER TABLE currencies 
  ADD UNIQUE INDEX currency_code(currency_code);

--
-- Create table `users`
--
CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(150) NOT NULL,
  currency_id INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE users 
  ADD CONSTRAINT FK_users FOREIGN KEY (currency_id)
    REFERENCES currencies(id);

--
-- Create table `categories_income`
--
CREATE TABLE categories_income (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  user_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE categories_income 
  ADD CONSTRAINT FK_categories_income FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `transactions_income`
--
CREATE TABLE transactions_income (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  date DATETIME NOT NULL,
  categories_income_id INT(11) NOT NULL,
  amount DOUBLE NOT NULL,
  currency_id INT(11) NOT NULL,
  comment TEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE transactions_income 
  ADD CONSTRAINT FK_transactions_income FOREIGN KEY (currency_id)
    REFERENCES currencies(id);

--
-- Create foreign key
--
ALTER TABLE transactions_income 
  ADD CONSTRAINT FK_transactions_income_categories_income_id FOREIGN KEY (categories_income_id)
    REFERENCES categories_income(id);

--
-- Create foreign key
--
ALTER TABLE transactions_income 
  ADD CONSTRAINT FK_transactions_income_users_id FOREIGN KEY (user_id)
    REFERENCES users(id);

--
-- Create table `categories_expense`
--
CREATE TABLE categories_expense (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  user_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE categories_expense 
  ADD CONSTRAINT FK_categories_expense FOREIGN KEY (user_id)
    REFERENCES users(id);

--
-- Create table `subcategories_expense`
--
CREATE TABLE subcategories_expense (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  categories_expense_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE subcategories_expense 
  ADD CONSTRAINT FK_subcategories_expense FOREIGN KEY (categories_expense_id)
    REFERENCES categories_expense(id);

--
-- Create table `transactions_expense`
--
CREATE TABLE transactions_expense (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  date DATETIME NOT NULL,
  categories_expense_id INT(11) NOT NULL,
  subcategories_expense_id INT(11) NOT NULL,
  amount DOUBLE NOT NULL,
  currency_id INT(11) NOT NULL,
  comment TEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE transactions_expense 
  ADD CONSTRAINT FK_transactions_expense FOREIGN KEY (currency_id)
    REFERENCES currencies(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE transactions_expense 
  ADD CONSTRAINT FK_transactions_expense_categories_expense_id FOREIGN KEY (categories_expense_id)
    REFERENCES categories_expense(id);

--
-- Create foreign key
--
ALTER TABLE transactions_expense 
  ADD CONSTRAINT FK_transactions_expense_subcategories_expense_id FOREIGN KEY (subcategories_expense_id)
    REFERENCES subcategories_expense(id);

--
-- Create foreign key
--
ALTER TABLE transactions_expense 
  ADD CONSTRAINT FK_transactions_expense_users_id FOREIGN KEY (user_id)
    REFERENCES users(id);

--
-- Create table `exchange`
--
CREATE TABLE exchange (
  currency_rate_id INT(11) NOT NULL AUTO_INCREMENT,
  currency_rate_date DATETIME NOT NULL,
  from_currency_code CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  to_currency_code CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  exchange_rate DOUBLE NOT NULL,
  PRIMARY KEY (currency_rate_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `currency_rate_date` on table `exchange`
--
ALTER TABLE exchange 
  ADD UNIQUE INDEX currency_rate_date(currency_rate_date);

--
-- Create index `from_currency_code` on table `exchange`
--
ALTER TABLE exchange 
  ADD UNIQUE INDEX from_currency_code(from_currency_code);

--
-- Create index `to_currency_code` on table `exchange`
--
ALTER TABLE exchange 
  ADD UNIQUE INDEX to_currency_code(to_currency_code);

-- 
-- Dumping data for table currencies
--
INSERT INTO currencies VALUES
(1, 'CAD', 'Canadian Dollar'),
(2, 'CHF', 'Swiss Franc'),
(3, 'EUR', 'European Euro'),
(4, 'GBP', 'British Pound'),
(5, 'HUF', 'Hungarian Forint'),
(6, 'JPY', 'Japanese Yen'),
(7, 'USD', 'U.S. Dollar');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'user1', 'user1@test.com', 'password', 1);

-- 
-- Dumping data for table categories_expense
--
-- Table `e-budget`.categories_expense does not contain any data (it is empty)

-- 
-- Dumping data for table categories_income
--
-- Table `e-budget`.categories_income does not contain any data (it is empty)

-- 
-- Dumping data for table subcategories_expense
--
-- Table `e-budget`.subcategories_expense does not contain any data (it is empty)

-- 
-- Dumping data for table transactions_income
--
-- Table `e-budget`.transactions_income does not contain any data (it is empty)

-- 
-- Dumping data for table transactions_expense
--
-- Table `e-budget`.transactions_expense does not contain any data (it is empty)

-- 
-- Dumping data for table exchange
--
-- Table `e-budget`.exchange does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;